"""Consume Ghidra's analysis_dump.json and produce RE artifacts.

Reads ``Metacache/Dev/RE/firmware/analysis_dump.json`` (produced by
``DumpAnalysis.java`` / ``run_ghidra_setup.ps1``) and emits:

- ``Metacache/Dev/RE/sub_command_dispatch.md``: every dispatch candidate with
  its mnemonic table, function address, decompile snippet, and the
  format strings each handler emits.
- Updated ``Metacache/Dev/RE/sub_command_response_map.md``: for each previously
  "untriggered" format string, fills in the trigger command if the
  responsible function maps back to a dispatch mnemonic.
- ``Metacache/Dev/RE/SDS100_inter_mcu_protocol.md``: bus identification (which
  peripherals are most-used + the function lists for UART1/SSP0), init
  function decompile, and frame-format hypotheses.
- ``Metacache/Dev/RE/sessions/dispatch_candidates.txt``: one mnemonic per line,
  ready for ``_verify_dispatch.py`` to falsify against the live scanner.

Pure Python 3, no dependencies on Ghidra, JPype, or any third-party
package. Reads the JSON dump from disk and post-processes.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
RE_DIR = REPO_ROOT / "AI" / "Dev" / "RE"
DEFAULT_DUMP = RE_DIR / "firmware" / "analysis_dump.json"

OUT_DISPATCH = RE_DIR / "sub_command_dispatch.md"
OUT_INTER_MCU = RE_DIR / "SDS100_inter_mcu_protocol.md"
OUT_RESPONSE_MAP = RE_DIR / "sub_command_response_map.md"
OUT_DISPATCH_LIST = RE_DIR / "sessions" / "dispatch_candidates.txt"


@dataclass(frozen=True)
class StringRec:
    addr: str
    value: str
    length: int
    is_format: bool
    xref_functions: tuple[str, ...]


@dataclass
class FunctionRec:
    addr: str
    name: str
    size: int
    callers: list[str]
    callees: list[str]
    peripheral_accesses: list[str]
    decompile: str = ""


@dataclass
class DispatchCandidate:
    function_addr: str
    function_name: str
    mnemonics: list[tuple[str, str]]


def load_dump(path: Path) -> dict:
    if not path.exists():
        sys.exit(f"[X] analysis dump not found: {path}\n"
                 f"    Run AI\\Dev\\RE\\automation\\run_ghidra_setup.ps1 first.")
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def parse_strings(dump: dict) -> dict[str, StringRec]:
    out: dict[str, StringRec] = {}
    for s in dump.get("strings", []):
        rec = StringRec(
            addr=s["addr"],
            value=s["value"],
            length=int(s.get("length", len(s["value"]))),
            is_format=bool(s.get("is_format", False)),
            xref_functions=tuple(s.get("xref_functions", [])),
        )
        out[rec.addr] = rec
    return out


def parse_functions(dump: dict) -> dict[str, FunctionRec]:
    out: dict[str, FunctionRec] = {}
    for f in dump.get("functions", []):
        rec = FunctionRec(
            addr=f["addr"],
            name=f.get("name", ""),
            size=int(f.get("size", 0)),
            callers=list(f.get("callers", [])),
            callees=list(f.get("callees", [])),
            peripheral_accesses=list(f.get("peripheral_accesses", [])),
            decompile=f.get("decompile", ""),
        )
        out[rec.addr] = rec
    return out


def parse_dispatch_candidates(dump: dict) -> list[DispatchCandidate]:
    out: list[DispatchCandidate] = []
    for c in dump.get("dispatch_candidates", []):
        out.append(
            DispatchCandidate(
                function_addr=c["function"],
                function_name=c.get("function_name", ""),
                mnemonics=[(m["value"], m["string_addr"]) for m in c.get("mnemonics", [])],
            )
        )
    out.sort(key=lambda c: -len(c.mnemonics))
    return out


def write_dispatch_md(
    candidates: list[DispatchCandidate],
    functions: dict[str, FunctionRec],
    strings: dict[str, StringRec],
    dump: dict,
) -> None:
    OUT_DISPATCH.parent.mkdir(parents=True, exist_ok=True)
    md = [
        "# SUB Command Dispatch Table (auto-generated)",
        "",
        f"> Generated by `_analyze_ghidra_dump.py` on {datetime.now(tz=timezone.utc).isoformat()}",
        f"> Source: `{DEFAULT_DUMP.relative_to(REPO_ROOT)}`",
        f"> Ghidra: {dump.get('metadata', {}).get('ghidra_version', '?')}",
        "",
        "Each entry below is a function whose body cross-references three or more",
        "short ASCII string literals that *look* like command mnemonics. The",
        "highest-cardinality candidate is almost certainly the SUB-port command",
        "dispatch routine. Validate empirically with `_verify_dispatch.py`.",
        "",
    ]

    if not candidates:
        md.append(
            "**No dispatch candidates found.** Either the firmware uses a "
            "hash-indexed lookup (which our heuristic can't see) or the "
            "auto-analysis didn't recover string xrefs. Re-run "
            "`run_ghidra_setup.ps1 -Force` after verifying SetupSubProject's "
            "memory-map setup actually ran."
        )
    else:
        md.append(f"## {len(candidates)} candidate functions, sorted by mnemonic count")
        md.append("")
        for i, c in enumerate(candidates, start=1):
            f = functions.get(c.function_addr)
            md.append(f"### Candidate {i}: function `{c.function_name or c.function_addr}` "
                      f"@ `{c.function_addr}`")
            md.append("")
            if f:
                md.append(f"- **Size**: {f.size} bytes")
                md.append(f"- **Callers** ({len(f.callers)}): "
                          + ", ".join(f"`{a}`" for a in f.callers[:8])
                          + ("…" if len(f.callers) > 8 else ""))
                md.append(f"- **Callees** ({len(f.callees)}): "
                          + ", ".join(f"`{a}`" for a in f.callees[:8])
                          + ("…" if len(f.callees) > 8 else ""))
                if f.peripheral_accesses:
                    md.append(f"- **Peripheral accesses**: {', '.join(f.peripheral_accesses)}")
            md.append(f"- **Mnemonic count**: {len(c.mnemonics)}")
            md.append("")
            md.append("| Mnemonic | String addr |")
            md.append("|---|---|")
            for value, saddr in c.mnemonics:
                escaped = value.replace("|", "\\|")
                md.append(f"| `{escaped}` | `{saddr}` |")
            md.append("")
            if f and f.decompile:
                md.append("<details><summary>Decompile (truncated)</summary>")
                md.append("")
                md.append("```c")
                md.append(f.decompile.rstrip())
                md.append("```")
                md.append("")
                md.append("</details>")
                md.append("")

    OUT_DISPATCH.write_text("\n".join(md) + "\n", encoding="utf-8")
    print(f"[+] wrote {OUT_DISPATCH.relative_to(REPO_ROOT)}")


def write_dispatch_candidates_txt(candidates: list[DispatchCandidate]) -> None:
    OUT_DISPATCH_LIST.parent.mkdir(parents=True, exist_ok=True)
    seen: set[str] = set()
    lines: list[str] = []
    for c in candidates:
        for value, _ in c.mnemonics:
            if value in seen:
                continue
            seen.add(value)
            lines.append(value)
    OUT_DISPATCH_LIST.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[+] wrote {OUT_DISPATCH_LIST.relative_to(REPO_ROOT)} "
          f"({len(lines)} unique mnemonics)")


def write_inter_mcu_md(
    functions: dict[str, FunctionRec],
    dump: dict,
) -> None:
    peripheral_users: dict[str, list[str]] = dump.get("peripheral_users", {})
    bus_candidates = sorted(
        (
            (name, addrs)
            for name, addrs in peripheral_users.items()
            if name.startswith(("USART", "SSP", "SPI", "I2C"))
        ),
        key=lambda kv: -len(kv[1]),
    )

    md = [
        "# SDS100 Inter-MCU Protocol (auto-generated draft)",
        "",
        f"> Generated by `_analyze_ghidra_dump.py` on {datetime.now(tz=timezone.utc).isoformat()}",
        "",
        "Heuristic: peripherals with the most function-touches are the prime",
        "candidates for the inter-MCU bus. UART/SSP/SPI/I2C are the only",
        "physically reasonable carriers; ADC/USB/Timer hits are noise.",
        "",
        "## Bus candidate ranking",
        "",
        "| Peripheral | Functions touching it | Likelihood |",
        "|---|---:|---|",
    ]
    for name, addrs in bus_candidates:
        verdict = "?"
        if len(addrs) >= 6:
            verdict = "**strong**"
        elif len(addrs) >= 3:
            verdict = "moderate"
        elif len(addrs) >= 1:
            verdict = "weak"
        md.append(f"| `{name}` | {len(addrs)} | {verdict} |")
    md.append("")

    if bus_candidates:
        primary = bus_candidates[0][0]
        md.append(f"## Primary candidate: `{primary}`")
        md.append("")
        md.append("Functions touching it:")
        md.append("")
        for addr in bus_candidates[0][1][:30]:
            f = functions.get(addr)
            if f:
                md.append(f"- `{addr}` ({f.name}, {f.size} bytes)")
            else:
                md.append(f"- `{addr}`")
        md.append("")
        md.append("### Init function decompile (largest function in the list)")
        md.append("")
        largest = max(
            (functions[a] for a in bus_candidates[0][1] if a in functions),
            key=lambda f: f.size,
            default=None,
        )
        if largest and largest.decompile:
            md.append(f"`{largest.addr}` ({largest.name}, {largest.size} bytes):")
            md.append("")
            md.append("```c")
            md.append(largest.decompile.rstrip())
            md.append("```")
            md.append("")
        else:
            md.append("(no decompile output available)")
            md.append("")

    md += [
        "## Frame-format hypothesis",
        "",
        "_Manually fill in once the init function reveals baud rate, parity,",
        "and word size. Search the decompile for writes to `*_DLL`, `*_DLM`,",
        "`*_LCR`, `*_FCR` (UART) or `CR0`, `CR1`, `CPSR` (SSP)._",
        "",
        "## Open questions",
        "",
        "- Does the SUB MCU initiate or only respond?",
        "- What is the wake-up packet (if any) for waking the SUB from sleep?",
        "- Is there a CRC / framing byte on the bus?",
        "",
    ]

    OUT_INTER_MCU.write_text("\n".join(md) + "\n", encoding="utf-8")
    print(f"[+] wrote {OUT_INTER_MCU.relative_to(REPO_ROOT)}")


def update_response_map(
    candidates: list[DispatchCandidate],
    strings: dict[str, StringRec],
    functions: dict[str, FunctionRec],
) -> None:
    """Best-effort: for each format-string, find the dispatch mnemonic
    whose handler function is the same as the format-string's xref
    function, and append a "Dispatch trigger:" annotation.

    We don't rewrite the existing file - we append a marked section.
    """
    if not OUT_RESPONSE_MAP.exists():
        print(f"[!] {OUT_RESPONSE_MAP.relative_to(REPO_ROOT)} not present; skipping response-map update.")
        return

    # Build a function-addr -> set(mnemonic) map from the dispatch.
    handler_for_mnemonic: dict[str, str] = {}
    for c in candidates:
        # In our heuristic we record the dispatch *function*, not the
        # individual handler. Still useful to know "this mnemonic is
        # handled inside function X".
        for value, _ in c.mnemonics:
            handler_for_mnemonic.setdefault(value, c.function_addr)

    fn_to_mnemonics: dict[str, list[str]] = defaultdict(list)
    for mnemonic, fn_addr in handler_for_mnemonic.items():
        fn_to_mnemonics[fn_addr].append(mnemonic)

    annotations: list[str] = []
    for s in strings.values():
        if not s.is_format:
            continue
        triggers: set[str] = set()
        for fn_addr in s.xref_functions:
            for m in fn_to_mnemonics.get(fn_addr, []):
                triggers.add(m)
        if triggers:
            annotations.append(
                f"- `{s.value}` (@ `{s.addr}`) -> dispatch fn touches: "
                f"{', '.join(sorted(f'`{t}`' for t in triggers))}"
            )

    block = [
        "",
        "<!-- begin auto-generated by _analyze_ghidra_dump.py -->",
        "## Auto-generated dispatch annotations",
        "",
        f"_Generated {datetime.now(tz=timezone.utc).isoformat()}_",
        "",
        ("Each line below is a format string whose containing function ALSO "
         "appears as a dispatch candidate above. The mnemonic(s) listed are "
         "the ones whose handler resides in the same dispatch routine - "
         "candidates for being the trigger that emits this format string."),
        "",
    ]
    if not annotations:
        block.append("_(no overlaps found)_")
    else:
        block.extend(annotations)
    block.append("")
    block.append("<!-- end auto-generated by _analyze_ghidra_dump.py -->")
    block.append("")

    text = OUT_RESPONSE_MAP.read_text(encoding="utf-8")
    # Strip any prior auto-generated block.
    text = re.sub(
        r"\n*<!-- begin auto-generated by _analyze_ghidra_dump\.py -->.*?<!-- end auto-generated by _analyze_ghidra_dump\.py -->\n*",
        "\n",
        text,
        flags=re.DOTALL,
    )
    if not text.endswith("\n"):
        text += "\n"
    text += "\n".join(block) + "\n"
    OUT_RESPONSE_MAP.write_text(text, encoding="utf-8")
    print(f"[+] updated {OUT_RESPONSE_MAP.relative_to(REPO_ROOT)} "
          f"({len(annotations)} annotations)")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--dump", type=Path, default=DEFAULT_DUMP, help="analysis_dump.json path")
    args = p.parse_args()

    dump = load_dump(args.dump)
    strings = parse_strings(dump)
    functions = parse_functions(dump)
    candidates = parse_dispatch_candidates(dump)

    meta = dump.get("metadata", {})
    print("[*] Loaded dump:")
    print(f"      ghidra={meta.get('ghidra_version', '?')}")
    print(f"      strings={len(strings)} (format={sum(1 for s in strings.values() if s.is_format)})")
    print(f"      functions={len(functions)}")
    print(f"      dispatch_candidates={len(candidates)}")
    print(f"      peripheral_users={list(dump.get('peripheral_users', {}).keys())}")

    write_dispatch_md(candidates, functions, strings, dump)
    write_dispatch_candidates_txt(candidates)
    write_inter_mcu_md(functions, dump)
    update_response_map(candidates, strings, functions)
    return 0


if __name__ == "__main__":
    sys.exit(main())
