"""Cross-correlate live probe responses with SUB firmware strings."""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import _common as _c  # noqa: E402

SESSIONS_DIR = _c.SESSIONS_DIR

_SUB_HIT_RE = re.compile(
    r"HIT\s+(\S+)\s+\d+B\s+in\s+[\d.]+\s+ms\s+\|\s+(.+)",
    re.MULTILINE,
)
_FMT_CONV_CHARS = frozenset("diouxXeEfgGsc")
_FMT_FLAG_CHARS = frozenset("-+ #0")
_FMT_LEN_CHARS = frozenset("hljztL")


def _parse_fmt_spec(fmt: str, start: int) -> tuple[str, int] | None:
    """Parse ``%...`` conversion at ``fmt[start:]``; return ``(conv, end_index)``."""
    if start >= len(fmt) or fmt[start] != "%":
        return None
    i = start + 1
    while i < len(fmt) and fmt[i] in _FMT_FLAG_CHARS:
        i += 1
    while i < len(fmt) and fmt[i].isdigit():
        i += 1
    if i < len(fmt) and fmt[i] == ".":
        i += 1
        while i < len(fmt) and fmt[i].isdigit():
            i += 1
    while i < len(fmt) and fmt[i] in _FMT_LEN_CHARS:
        i += 1
    if i >= len(fmt) or fmt[i] not in _FMT_CONV_CHARS:
        return None
    return fmt[i], i + 1


def collect_sub_hits() -> list[tuple[str, str]]:
    hits: list[tuple[str, str]] = []
    seen: set[str] = set()
    for log in sorted(SESSIONS_DIR.glob("sub_probe_*.txt")):
        if "summary" in log.name or "stdout" in log.name:
            continue
        text = log.read_text(encoding="utf-8", errors="replace")
        for cmd, resp in _SUB_HIT_RE.findall(text):
            key = f"{cmd}|{resp}"
            if key in seen:
                continue
            seen.add(key)
            hits.append((cmd, resp))
    return hits


def load_strings(strings_file: Path) -> list[str]:
    if not strings_file.exists():
        return []
    return [
        line.strip()
        for line in strings_file.read_text(encoding="utf-8", errors="replace").splitlines()
        if line.strip()
    ]


def _conversion_pattern(conv: str) -> str:
    if conv in ("d", "i"):
        return r"-?\s*\d+"
    if conv in ("u", "o"):
        return r"\d+"
    if conv in ("x", "X"):
        return r"[0-9a-fA-F]+"
    if conv in ("e", "E", "f", "g", "G"):
        return r"-?\d+(?:\.\d+)?(?:[eE]-?\d+)?"
    if conv == "c":
        return r"."
    return r"\S+"


def fmt_to_regex(fmt: str) -> re.Pattern | None:
    parts: list[str] = []
    i = 0
    has_spec = False
    while i < len(fmt):
        c = fmt[i]
        if c == "%":
            if i + 1 < len(fmt) and fmt[i + 1] == "%":
                parts.append("%")
                i += 2
                continue
            parsed = _parse_fmt_spec(fmt, i)
            if not parsed:
                parts.append(re.escape(c))
                i += 1
                continue
            has_spec = True
            conv, i = parsed
            parts.append(_conversion_pattern(conv))
        else:
            parts.append(re.escape(c))
            i += 1
    if not has_spec:
        return None
    try:
        return re.compile("".join(parts))
    except re.error:
        return None


def find_mnemonic_in_payload(mnemonic: str, payload: bytes) -> list[int]:
    needle = mnemonic.encode("ascii") + b"\x00"
    out: list[int] = []
    i = 0
    while True:
        j = payload.find(needle, i)
        if j < 0:
            break
        out.append(j)
        i = j + 1
    return out


def _normalize_response(resp: str) -> str:
    cleaned = resp.replace("\\r", "\r").replace("\\n", "\n").replace("\\t", "\t")
    return re.sub(r"<\\x[0-9A-Fa-f]{2}>", "?", cleaned)


def _match_hit(
    cmd: str,
    resp: str,
    fmt_patterns: list[tuple[str, re.Pattern]],
    payload: bytes,
) -> dict:
    cleaned = _normalize_response(resp)
    per_cmd_matches = [fmt for fmt, pat in fmt_patterns if pat.search(cleaned)]
    head = cmd.split(",", 1)[0]
    return {
        "cmd": cmd,
        "response": resp,
        "matched_strings": per_cmd_matches,
        "mnemonic_offsets": find_mnemonic_in_payload(head, payload),
    }


def _write_markdown_report(
    out_map: Path,
    *,
    sub_hits: list[tuple[str, str]],
    strings: list[str],
    fmt_patterns: list[tuple[str, re.Pattern]],
    matches: list[dict],
) -> None:
    n_with_match = sum(1 for m in matches if m["matched_strings"])
    n_with_xref = sum(1 for m in matches if m["mnemonic_offsets"])
    with out_map.open("w", encoding="utf-8") as f:
        f.write("# Sub command -> firmware string correlation map\n\n")
        f.write(
            "Generated by `_correlate_responses.py` from Phase 1-3 session "
            "logs and the Sub firmware strings table.\n\n"
        )
        f.write(f"- SUB-probe unique hits: {len(sub_hits)}\n")
        f.write(f"- Sub firmware strings: {len(strings)}\n")
        f.write(f"- Format strings (with %specifiers): {len(fmt_patterns)}\n")
        f.write(f"- Hits with response matching a format string: {n_with_match}\n")
        f.write(f"- Hits with mnemonic xref in payload: {n_with_xref}\n\n")
        f.write("## Per-command join\n\n")
        f.write("| Cmd | Response | Format-string matches | Payload offsets |\n")
        f.write("| --- | --- | --- | --- |\n")
        for m in matches:
            cmd = f"`{m['cmd']}`"
            resp = m["response"][:60].replace("|", "\\|")
            fs = "; ".join(f"`{s}`" for s in m["matched_strings"][:3])
            if len(m["matched_strings"]) > 3:
                fs += f" (+{len(m['matched_strings']) - 3} more)"
            offs = ", ".join(f"`0x{o:05x}`" for o in m["mnemonic_offsets"][:5])
            if len(m["mnemonic_offsets"]) > 5:
                offs += f" (+{len(m['mnemonic_offsets']) - 5})"
            f.write(f"| {cmd} | `{resp}` | {fs or '-'} | {offs or '-'} |\n")
        f.write("\n## Unmatched format strings (hypothesis targets)\n\n")
        triggered_fmts = {fmt for m in matches for fmt in m["matched_strings"]}
        untriggered = [(fmt, pat) for fmt, pat in fmt_patterns if fmt not in triggered_fmts]
        f.write(f"- Total format strings: {len(fmt_patterns)}\n")
        f.write(f"- Triggered: {len(fmt_patterns) - len(untriggered)}\n")
        f.write(f"- Untriggered: {len(untriggered)}\n\n")
        f.write("| Format string |\n")
        f.write("| --- |\n")
        for fmt, _pat in untriggered:
            short = fmt.replace("|", "\\|")[:120]
            f.write(f"| `{short}` |\n")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    _c.add_firmware_arg(p)
    p.add_argument("--strings", type=Path, default=None)
    p.add_argument("--output", "-o", type=Path, default=_c.DOCS_DIR / "sub_command_response_map.md")
    args = p.parse_args()

    fw_path = _c.resolve_firmware(args)
    payload = fw_path.read_bytes()
    strings_file = args.strings or _c.find_latest_sub_strings()
    if not strings_file:
        sys.exit("[X] No SUB strings dump found.")
    strings_file = _c.safe_user_path(_c.RE_ROOT, strings_file)
    out_map = _c.safe_user_path(_c.RE_ROOT, args.output)
    out_map.parent.mkdir(parents=True, exist_ok=True)

    sub_hits = collect_sub_hits()
    strings = load_strings(strings_file)
    fmt_patterns = [(s, pat) for s in strings if (pat := fmt_to_regex(s)) is not None]
    matches = [_match_hit(cmd, resp, fmt_patterns, payload) for cmd, resp in sub_hits]

    print(f"# Loaded {len(sub_hits)} unique SUB-probe hits")
    print(f"# {sum(1 for m in matches if m['matched_strings'])} commands matched a firmware format string")
    _write_markdown_report(out_map, sub_hits=sub_hits, strings=strings,
                           fmt_patterns=fmt_patterns, matches=matches)
    print(f"# Wrote {out_map}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
